# Generated by Django 4.2 on 2023-05-02 19:10

import django.utils.timezone
from django.db import migrations

import src.apps.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=src.apps.core.models.AutoDateTimeField(
                default=django.utils.timezone.now
            ),
        ),
    ]
