name: Linting
on: push
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-all-dev build-essential libpcre3-dev libpq-dev libcurl4-openssl-dev libssl-dev
        python -m pip install -U pip wheel
        pip install -r requirements/dev.txt
    - name: flake8
      run: flake8 src/ tests/
    - name: isort
      run: isort --profile black --check-only src/ tests/
    - name: black
      run: black --check src/ tests/
